[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:pyftpdlib.*
    ignore:The asyncore module:DeprecationWarning
    ignore:The asynchat module:DeprecationWarning
    ignore:write permissions assigned to anonymous user:RuntimeWarning
